apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotenberg-deploy
spec:
  selector:
    matchLabels:
      app: gotenberg
  template:
    metadata:
      labels:
        app: gotenberg
    spec:
      containers:
      - name: gotenberg
        image: docker.io/gotenberg/gotenberg:8.20
        command:
          - "gotenberg"
          - "--chromium-disable-javascript=true"
          - "--chromium-allow-list=file:///tmp/.*"
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        ports:
        - containerPort: 3000
          name: http
