apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookcstack-db-pvc
  annotations:
    # Do NOT accidentally delete the database:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: ceph-csi-cephfs
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
