apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - bookstack-cfg-staging.yaml

patches:
  - target:
      kind: Ingress
      name: bookstack-ig
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: wiki.staging.joris.me
