apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # Specify Gotenberg replicas
  - target:
      kind: Deployment
      name: gotenberg-deploy
    patch: |-
      - op: add
        path: /spec/replicas
        value: 2
  
  # Set PG replicas to 3
  - target:
      kind: Cluster
      name: postgres-cluster
    patch: |-
      - op: replace
        path: /spec/instances
        value: 3
