apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
spec:
  selector:
    matchLabels:
      app: tika
  template:
    metadata:
      labels:
        app: tika
    spec:
      containers:
      - name: tika
        image: docker.io/apache/tika:latest
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "2000m"
            memory: "1024Mi"
        ports:
        - containerPort: 9998
          name: http
