apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.30.0/controller.yaml

patches:
  - path: change-metadata-ns.json
    target:
      kind: Role
  - path: change-metadata-ns.json
    target:
      kind: ServiceAccount
  - path: change-metadata-ns.json
    target:
      kind: RoleBinding
  - path: change-metadata-ns.json
    target:
      kind: Service
  - path: change-metadata-ns.json
    target:
      kind: Deployment
  - path: change-subject-ns.json
    target:
      kind: ClusterRoleBinding
  - path: change-subject-ns.json
    target:
      kind: RoleBinding
