apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
spec:
  storageClassName: ceph-csi-cephfs
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
