apiVersion: v1
kind: Secret
metadata:
    name: kutt-app-secret
    namespace: kutt
type: Opaque
stringData:
    # secret
    JWT_SECRET: ENC[AES256_GCM,data:krLY8pecOgtD07tQt5wrssDIlSaAEISHbFQXbwrXoksjE6j7KCWZSPVWwsI=,iv:Za3o+GSBirSZVV4mIb5B0mKoV2SRIAMeJnYmoF3PeEs=,tag:wTD0VgC0LuC2tdfW9B6hsQ==,type:str]
sops:
    lastmodified: "2025-08-02T16:52:04Z"
    mac: ENC[AES256_GCM,data:vrNQEOP6sA35FrChaEvwQqMbgavr+NL9oK+L3lYanm0+7A0lOKAU9a4xdJrNYdqztI9ox80To/TVJN7XBPyhc73Jb4ZyLfY9FQNFZPZuZ1zonVWVsexDFhh3uYqU3x6AnZNMoWTQmEdPfgjja54qsmmJqD1w73CYnlcM8q/hzFk=,iv:8y4+P/uTab0BUAr5AjctRDI9hWw690pAcx+9jHwkaF8=,tag:RuSobJDLYkVkHdXr0fYxOw==,type:str]
    pgp:
        - created_at: "2025-08-02T16:52:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DOSLw1rOxnykSAQdA2izjAcK9ctJ61cm8+wcUpbr4vLG0jL/zwmlEtgaTnEIw
            /XtFG/lyqs1KYORwm08dSS8Hr1pCT42JjZj6tJn7q2D2MITHTMxvf0twSkMF7i8Z
            0l4BpBkcjGnyQX9se4iewT4Mik1RvXKeGHLz82Da17qZtj9EzUFZojC/zhY733wq
            1SRLQ5DgzsIQXx2UCK4K2necwj+WDHO9JCmbbJQlebf6Rg0EGqsR8GewBY1FYVGH
            =MwZy
            -----END PGP MESSAGE-----
          fp: C0B224C0F27D4BD397DB7AD23922F0D6B3B19F29!
        - created_at: "2025-08-02T16:52:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DQj/fwcZAP5kSAQdAq/WxhmlcFKNWfXAf49l3quzulknXXoir4sKSOFu3Rh0w
            OGV+eN3KzJ/OUz2oQgOCMbRdHnwpEplAAZG6IBIoo7LeSV7Lr3So9LA9c7d2RYqG
            0l4B/hqqYWhn8lFjleIays0sGeK+uP6lpSGkXEyFFFl+5v/X5VtjgVKxOi+X2PLg
            EAeL46eGSMtQmaUbjheSCCjWvSs49QDDc2JD6Y62ELQabdGzVDd7Y+cDXodecUH8
            =wGdx
            -----END PGP MESSAGE-----
          fp: A07340A6AC042B09AAA7F402423FDFC1C6403F99!
    encrypted_comment_regex: \s*(enc|encrypt|secret)(:\s*)?.*
    version: 3.10.2
