apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
    - group: '*'
      kind: '*'
      jsonPointers:
        - /sops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
  source:
    repoURL: https://github.com/joriskt/homelab-k8s-apps.git
    targetRevision: HEAD
    path: apps/paperless/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: paperless
