apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - kutt-app-cfg.yaml
  - ingress-go-joris.yaml
  - ingress-08.yaml

patches:
  # Set app replicas to 2
  - patch: |-
      op: add
      path: /spec/replicas
      value: 2
    target:
      name: kutt-app-deploy
      kind: Deployment

  # Set DB replicas to 3
  - patch: |-
      op: replace
      path: /spec/instances
      value: 3
    target:
      name: kutt-db-cluster
      kind: Cluster
