apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/joriskt/homelab-k8s-apps.git
    targetRevision: HEAD
    path: hello/base # Overriden per env to replace /base with /overlays/{env}
  destination:
    server: https://kubernetes.default.svc
    namespace: hello
