apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # Patch the hostname for GRPC connections
  - path: patch/ingress-grpc.json
    target:
      kind: Ingress
      name: argocd-server-grpc-ingress
  
  - path: patch/ingress-http.json
    target:
      kind: Ingress
      name: argocd-server-http-ingress