apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ntfy-deploy.yaml
  - ntfy-cache-pvc.yaml
  - ntfy-svc.yaml
  - ntfy-ingress.yaml

configMapGenerator:
  - name: ntfy-config
    files:
      - config/server.yml

generatorOptions:
  disableNameSuffixHash: true
