apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-cache-pvc
spec:
  storageClassName: ceph-csi-cephfs
  resources:
    requests:
      storage: 10G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
