apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copyparty-pvc
spec:
  storageClassName: ceph-csi-cephfs
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
