apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstack-cfg
data:
  APP_URL: https://wiki.joris.me
  OIDC_NAME: login.joris.me
  OIDC_ISSUER: https://login.joris.me/application/o/bookstack/
  AUTH_AUTO_INITIATE: "false"
  OIDC_ISSUER_DISCOVER: "true"
  OIDC_USER_TO_GROUPS: "true"
  OIDC_DISPLAY_NAME_CLAIMS: "preferred_username"
  OIDC_GROUPS_CLAIM: "groups"
  OIDC_REMOVE_FROM_GROUPS: "true"
  OIDC_DUMP_USER_DETAILS: "false"
  APP_DEFAULT_DARK_MODE: "true"
  APP_VIEWS_BOOKS: "list"
  CACHE_DRIVER: database
  SESSION_DRIVER: database
