apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - bookstack-cfg.yaml
  - bookstack-ig-prod.yaml
  - bookstack-ig-public.yaml

patches:
  - target:
      kind: Ingress
      name: bookstack-ig
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: wiki.prod.joris.me
  - target:
      kind: Deployment
      name: bookstack
    patch: |-
      - op: add
        path: /spec/replicas
        value: 1
    # Kan nog niet HA, daarvoor moet de PVC ReadWriteMany zijn en logs e.d. in een tmpfs landen
    # ipv op de PVC.